kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-1
          emptyDir: {}
      containers:
        - name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              protocol: TCP
            - containerPort: 33060
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: mysql-1
              mountPath: /var/lib/mysql
          image: quay.io/prajwal_gawande/mysql:5.7
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: 3306-tcp
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: 33060-tcp
      protocol: TCP
      port: 33060
      targetPort: 33060
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: mysql


