kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-mysql 
  labels:
    app: python-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-mysql
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: python-mysql
    spec:
      containers:
      - name: python-mysql
        image: quay.io/prajwal_gawande/python-mysql:2.0
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: mysql-url
          - name: mysql-root-password
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-root-password
                
---

kind: Service
apiVersion: v1
metadata:
  name: python-mysql
  labels:
    app: python-mysql
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: python-mysql
  type: NodePort

