kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-mysql 
  labels:
    app: python-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-mysql
  template:
    metadata:
      labels:
        app: python-mysql
    spec:
      containers:
        - name: python-mysql
          image: quay.io/prajwal_gawande/python-mysql:1.0
          ports:
            - containerPort: 5000
              protocol: TCP
---

kind: Service
apiVersion: v1
metadata:
  name: python-mysql
  labels:
    app: python-mysql
spec:
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: python-mysql

